#!/usr/bin/env bash

editor=${EDITOR:-nano}

cmd_dir=~/.local/repo-cmd/`git rev-parse --show-toplevel`
[ "$?" -eq "0" ] || exit 1

if [[ ! -f $cmd_dir/exec.bash ]]; then
    mkdir -p $cmd_dir
    echo \
'#!/usr/bin/env bash

case $1 in
*)
    echo "$1 not implemented"
    ;;
esac
' > $cmd_dir/exec.bash || exit 1
    chmod +x $cmd_dir/exec.bash || exit 1
fi

case $1 in
edit)
    $editor $cmd_dir/exec.bash
    ;;
print)
    if [[ $# -gt 1 ]]; then
        sed -n "/^\s*$2)/,/;;/p" $cmd_dir/exec.bash
    else
        grep ')$' $cmd_dir/exec.bash
        echo notes: `ls $cmd_dir | grep "notes"`
    fi
    ;;
notes.*)
    $EDITOR $cmd_dir/notes.${1#"notes."}
    ;;
*)
    $cmd_dir/exec.bash "$@"
    ;;
esac
