#!/usr/bin/env bash

if [[ "$#" -lt 1 ]]; then
    echo "usage: repo-cmd COMMAND [COMMAND_ARG]

where COMMAND is one of:
- edit
- print
- notes.<any extension>
- any command specified in the repo commands' script

# edit
modify the repo commands' script

# print
print all commands available (and all so far written notes extensions)

# notes.<any extension>
open an editor for quick notes (or eg for storing some useful database queries)
"
    exit 1
fi

repo_root=`git rev-parse --show-toplevel`
cd "$repo_root"
cmd_dir=~/.local/repo-cmd/"$repo_root"
[ "$?" -eq "0" ] || exit 1

if [[ ! -f "$cmd_dir"/exec.bash ]]; then
    mkdir -p "$cmd_dir"
    echo \
'#!/usr/bin/env bash

case $1 in
*)
    echo "$1 not implemented"
    ;;
esac
' > "$cmd_dir"/exec.bash || exit 1
    chmod +x "$cmd_dir"/exec.bash || exit 1
fi

editor=${EDITOR:-vim}

case $1 in
edit)
    $editor "$cmd_dir"/exec.bash
    ;;
print)
    if [[ $# -gt 1 ]]; then
        sed -n "/^\s*$2)/,/;;/p" "$cmd_dir"/exec.bash
    else
        grep ')$' "$cmd_dir"/exec.bash
        echo notes: `ls "$cmd_dir" | grep "notes"`
    fi
    ;;
notes.*)
    $editor "$cmd_dir/notes.${1#'notes.'}"
    ;;
*)
    "$cmd_dir"/exec.bash "$@"
    ;;
esac
